### ISSUE TITLE
CMAC support?

### ISSUE THREAD

**Issue by beevik** [ericlagergren/siv#6]
I am working on a [project](https://github.com/beevik/ntp) that requires [AEAD_AES_SIV_CMAC_256](https://www.rfc-editor.org/rfc/rfc8915.html#RFC5297). I discovered your project but found that it does not implement AEAD_AES_SIV_CMAC_256. Can you comment on what modifications to your project would be required to support this algorithm?

**Comment by ericlagergren** [comment]
Hi, they are quite different constructions.

Here is a Go implementation of AES-SIV-CMAC: https://github.com/secure-io/siv-go

The author is reputable, but I cannot vouch for the code itself.

**Comment by ericlagergren** [comment]
I may add AES-SIV-CMAC support at some point, but I currently do not have plans to do so. Sorry.

**Comment by beevik** [comment]
Thanks for the response.
